// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ranxfydxwizqrdklxcwv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJhbnhmeWR4d2l6cXJka2x4Y3d2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NDgxNDQsImV4cCI6MjA1OTUyNDE0NH0.EGslqyglMFWNTypgOHGV7Iyt-B_vPzw2cSViOq_chkI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);